title: Devsta
description: Blog about my program development, etc...
url: https://sharaelong.github.io
author: kijun Shin

markdown: CommonMarkGhPages

collections:
  authors:
    output: true

excerpt-separator: <!--more-->

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed